COCOS2DX_ROOT=$$PWD/../..

SOURCES += \
    $$COCOS2DX_ROOT/cocos/base/allocator/CCAllocatorDiagnostics.cpp \
    $$COCOS2DX_ROOT/cocos/base/allocator/CCAllocatorGlobal.cpp \
    $$COCOS2DX_ROOT/cocos/base/allocator/CCAllocatorGlobalNewDelete.cpp \
    $$COCOS2DX_ROOT/cocos/base/atitc.cpp \
    $$COCOS2DX_ROOT/cocos/base/base64.cpp \
    $$COCOS2DX_ROOT/cocos/base/CCAsyncTaskPool.cpp \
    $$COCOS2DX_ROOT/cocos/base/CCAutoreleasePool.cpp \
    $$COCOS2DX_ROOT/cocos/base/ccCArray.cpp \
    $$COCOS2DX_ROOT/cocos/base/CCConfiguration.cpp \
    $$COCOS2DX_ROOT/cocos/base/CCConsole.cpp \
    $$COCOS2DX_ROOT/cocos/base/CCController.cpp \
    $$COCOS2DX_ROOT/cocos/base/CCData.cpp \
    $$COCOS2DX_ROOT/cocos/base/CCDataVisitor.cpp \
    $$COCOS2DX_ROOT/cocos/base/CCDirector.cpp \
    $$COCOS2DX_ROOT/cocos/base/CCEvent.cpp \
    $$COCOS2DX_ROOT/cocos/base/CCEventAcceleration.cpp \
    $$COCOS2DX_ROOT/cocos/base/CCEventController.cpp \
    $$COCOS2DX_ROOT/cocos/base/CCEventCustom.cpp \
    $$COCOS2DX_ROOT/cocos/base/CCEventDispatcher.cpp \
    $$COCOS2DX_ROOT/cocos/base/CCEventFocus.cpp \
    $$COCOS2DX_ROOT/cocos/base/CCEventKeyboard.cpp \
    $$COCOS2DX_ROOT/cocos/base/CCEventListener.cpp \
    $$COCOS2DX_ROOT/cocos/base/CCEventListenerAcceleration.cpp \
    $$COCOS2DX_ROOT/cocos/base/CCEventListenerController.cpp \
    $$COCOS2DX_ROOT/cocos/base/CCEventListenerCustom.cpp \
    $$COCOS2DX_ROOT/cocos/base/CCEventListenerFocus.cpp \
    $$COCOS2DX_ROOT/cocos/base/CCEventListenerKeyboard.cpp \
    $$COCOS2DX_ROOT/cocos/base/CCEventListenerMouse.cpp \
    $$COCOS2DX_ROOT/cocos/base/CCEventListenerTouch.cpp \
    $$COCOS2DX_ROOT/cocos/base/CCEventMouse.cpp \
    $$COCOS2DX_ROOT/cocos/base/CCEventTouch.cpp \
    $$COCOS2DX_ROOT/cocos/base/CCIMEDispatcher.cpp \
    $$COCOS2DX_ROOT/cocos/base/CCNinePatchImageParser.cpp \
    $$COCOS2DX_ROOT/cocos/base/CCNS.cpp \
    $$COCOS2DX_ROOT/cocos/base/CCProfiling.cpp \
    $$COCOS2DX_ROOT/cocos/base/CCProperties.cpp \
    $$COCOS2DX_ROOT/cocos/base/ccRandom.cpp \
    $$COCOS2DX_ROOT/cocos/base/CCRef.cpp \
    $$COCOS2DX_ROOT/cocos/base/CCScheduler.cpp \
    $$COCOS2DX_ROOT/cocos/base/CCScriptSupport.cpp \
    $$COCOS2DX_ROOT/cocos/base/CCStencilStateManager.cpp \
    $$COCOS2DX_ROOT/cocos/base/CCTouch.cpp \
    $$COCOS2DX_ROOT/cocos/base/ccTypes.cpp \
    $$COCOS2DX_ROOT/cocos/base/ccUTF8.cpp \
    $$COCOS2DX_ROOT/cocos/base/ccUtils.cpp \
    $$COCOS2DX_ROOT/cocos/base/CCValue.cpp \
    $$COCOS2DX_ROOT/cocos/base/etc1.cpp \
    $$COCOS2DX_ROOT/cocos/base/ObjectFactory.cpp \
    $$COCOS2DX_ROOT/cocos/base/pvr.cpp \
    $$COCOS2DX_ROOT/cocos/base/s3tc.cpp \
    $$COCOS2DX_ROOT/cocos/base/TGAlib.cpp \
    $$COCOS2DX_ROOT/cocos/base/ZipUtils.cpp \
    $$COCOS2DX_ROOT/cocos/base/ccFPSImages.c \

HEADERS += \
    $$COCOS2DX_ROOT/cocos/base/allocator/CCAllocatorBase.h \
    $$COCOS2DX_ROOT/cocos/base/allocator/CCAllocatorDiagnostics.h \
    $$COCOS2DX_ROOT/cocos/base/allocator/CCAllocatorGlobal.h \
    $$COCOS2DX_ROOT/cocos/base/allocator/CCAllocatorMacros.h \
    $$COCOS2DX_ROOT/cocos/base/allocator/CCAllocatorMutex.h \
    $$COCOS2DX_ROOT/cocos/base/allocator/CCAllocatorStrategyDefault.h \
    $$COCOS2DX_ROOT/cocos/base/allocator/CCAllocatorStrategyFixedBlock.h \
    $$COCOS2DX_ROOT/cocos/base/allocator/CCAllocatorStrategyGlobalSmallBlock.h \
    $$COCOS2DX_ROOT/cocos/base/allocator/CCAllocatorStrategyPool.h \
    $$COCOS2DX_ROOT/cocos/base/atitc.h \
    $$COCOS2DX_ROOT/cocos/base/base64.h \
    $$COCOS2DX_ROOT/cocos/base/CCAsyncTaskPool.h \
    $$COCOS2DX_ROOT/cocos/base/CCAutoreleasePool.h \
    $$COCOS2DX_ROOT/cocos/base/ccCArray.h \
    $$COCOS2DX_ROOT/cocos/base/ccConfig.h \
    $$COCOS2DX_ROOT/cocos/base/CCConfiguration.h \
    $$COCOS2DX_ROOT/cocos/base/CCConsole.h \
    $$COCOS2DX_ROOT/cocos/base/CCController.h \
    $$COCOS2DX_ROOT/cocos/base/CCData.h \
    $$COCOS2DX_ROOT/cocos/base/CCDataVisitor.h \
    $$COCOS2DX_ROOT/cocos/base/CCDirector.h \
    $$COCOS2DX_ROOT/cocos/base/CCEvent.h \
    $$COCOS2DX_ROOT/cocos/base/CCEventAcceleration.h \
    $$COCOS2DX_ROOT/cocos/base/CCEventController.h \
    $$COCOS2DX_ROOT/cocos/base/CCEventCustom.h \
    $$COCOS2DX_ROOT/cocos/base/CCEventDispatcher.h \
    $$COCOS2DX_ROOT/cocos/base/CCEventFocus.h \
    $$COCOS2DX_ROOT/cocos/base/CCEventKeyboard.h \
    $$COCOS2DX_ROOT/cocos/base/CCEventListener.h \
    $$COCOS2DX_ROOT/cocos/base/CCEventListenerAcceleration.h \
    $$COCOS2DX_ROOT/cocos/base/CCEventListenerController.h \
    $$COCOS2DX_ROOT/cocos/base/CCEventListenerCustom.h \
    $$COCOS2DX_ROOT/cocos/base/CCEventListenerFocus.h \
    $$COCOS2DX_ROOT/cocos/base/CCEventListenerKeyboard.h \
    $$COCOS2DX_ROOT/cocos/base/CCEventListenerMouse.h \
    $$COCOS2DX_ROOT/cocos/base/CCEventListenerTouch.h \
    $$COCOS2DX_ROOT/cocos/base/CCEventMouse.h \
    $$COCOS2DX_ROOT/cocos/base/CCEventTouch.h \
    $$COCOS2DX_ROOT/cocos/base/CCEventType.h \
    $$COCOS2DX_ROOT/cocos/base/ccFPSImages.h \
    $$COCOS2DX_ROOT/cocos/base/CCGameController.h \
    $$COCOS2DX_ROOT/cocos/base/CCIMEDelegate.h \
    $$COCOS2DX_ROOT/cocos/base/CCIMEDispatcher.h \
    $$COCOS2DX_ROOT/cocos/base/ccMacros.h \
    $$COCOS2DX_ROOT/cocos/base/CCMap.h \
    $$COCOS2DX_ROOT/cocos/base/CCNinePatchImageParser.h \
    $$COCOS2DX_ROOT/cocos/base/CCNS.h \
    $$COCOS2DX_ROOT/cocos/base/CCProfiling.h \
    $$COCOS2DX_ROOT/cocos/base/CCProperties.h \
    $$COCOS2DX_ROOT/cocos/base/CCProtocols.h \
    $$COCOS2DX_ROOT/cocos/base/ccRandom.h \
    $$COCOS2DX_ROOT/cocos/base/CCRef.h \
    $$COCOS2DX_ROOT/cocos/base/CCRefPtr.h \
    $$COCOS2DX_ROOT/cocos/base/CCScheduler.h \
    $$COCOS2DX_ROOT/cocos/base/CCScriptSupport.h \
    $$COCOS2DX_ROOT/cocos/base/CCStencilStateManager.h \
    $$COCOS2DX_ROOT/cocos/base/CCTouch.h \
    $$COCOS2DX_ROOT/cocos/base/ccTypes.h \
    $$COCOS2DX_ROOT/cocos/base/CCUserDefault.h \
    $$COCOS2DX_ROOT/cocos/base/ccUTF8.h \
    $$COCOS2DX_ROOT/cocos/base/ccUtils.h \
    $$COCOS2DX_ROOT/cocos/base/CCValue.h \
    $$COCOS2DX_ROOT/cocos/base/CCVector.h \
    $$COCOS2DX_ROOT/cocos/base/etc1.h \
    $$COCOS2DX_ROOT/cocos/base/firePngData.h \
    $$COCOS2DX_ROOT/cocos/base/ObjectFactory.h \
    $$COCOS2DX_ROOT/cocos/base/pvr.h \
    $$COCOS2DX_ROOT/cocos/base/s3tc.h \
    $$COCOS2DX_ROOT/cocos/base/TGAlib.h \
    $$COCOS2DX_ROOT/cocos/base/uthash.h \
    $$COCOS2DX_ROOT/cocos/base/utlist.h \
    $$COCOS2DX_ROOT/cocos/base/ZipUtils.h
