COCOS2DX_ROOT=$$PWD/../../..

SOURCES += \
    $$COCOS2DX_ROOT/cocos/editor-support/spine/AttachmentVertices.cpp \
    $$COCOS2DX_ROOT/cocos/editor-support/spine/Cocos2dAttachmentLoader.cpp \
    $$COCOS2DX_ROOT/cocos/editor-support/spine/SkeletonAnimation.cpp \
    $$COCOS2DX_ROOT/cocos/editor-support/spine/SkeletonBatch.cpp \
    $$COCOS2DX_ROOT/cocos/editor-support/spine/SkeletonRenderer.cpp \
    $$COCOS2DX_ROOT/cocos/editor-support/spine/spine-cocos2dx.cpp \
    $$COCOS2DX_ROOT/cocos/editor-support/spine/Animation.c \
    $$COCOS2DX_ROOT/cocos/editor-support/spine/AnimationState.c \
    $$COCOS2DX_ROOT/cocos/editor-support/spine/AnimationStateData.c \
    $$COCOS2DX_ROOT/cocos/editor-support/spine/Atlas.c \
    $$COCOS2DX_ROOT/cocos/editor-support/spine/AtlasAttachmentLoader.c \
    $$COCOS2DX_ROOT/cocos/editor-support/spine/Attachment.c \
    $$COCOS2DX_ROOT/cocos/editor-support/spine/AttachmentLoader.c \
    $$COCOS2DX_ROOT/cocos/editor-support/spine/Bone.c \
    $$COCOS2DX_ROOT/cocos/editor-support/spine/BoneData.c \
    $$COCOS2DX_ROOT/cocos/editor-support/spine/BoundingBoxAttachment.c \
    $$COCOS2DX_ROOT/cocos/editor-support/spine/Event.c \
    $$COCOS2DX_ROOT/cocos/editor-support/spine/EventData.c \
    $$COCOS2DX_ROOT/cocos/editor-support/spine/extension.c \
    $$COCOS2DX_ROOT/cocos/editor-support/spine/IkConstraint.c \
    $$COCOS2DX_ROOT/cocos/editor-support/spine/IkConstraintData.c \
    $$COCOS2DX_ROOT/cocos/editor-support/spine/Json.c \
    $$COCOS2DX_ROOT/cocos/editor-support/spine/MeshAttachment.c \
    $$COCOS2DX_ROOT/cocos/editor-support/spine/PathAttachment.c \
    $$COCOS2DX_ROOT/cocos/editor-support/spine/PathConstraint.c \
    $$COCOS2DX_ROOT/cocos/editor-support/spine/PathConstraintData.c \
    $$COCOS2DX_ROOT/cocos/editor-support/spine/RegionAttachment.c \
    $$COCOS2DX_ROOT/cocos/editor-support/spine/Skeleton.c \
    $$COCOS2DX_ROOT/cocos/editor-support/spine/SkeletonBinary.c \
    $$COCOS2DX_ROOT/cocos/editor-support/spine/SkeletonBounds.c \
    $$COCOS2DX_ROOT/cocos/editor-support/spine/SkeletonData.c \
    $$COCOS2DX_ROOT/cocos/editor-support/spine/SkeletonJson.c \
    $$COCOS2DX_ROOT/cocos/editor-support/spine/Skin.c \
    $$COCOS2DX_ROOT/cocos/editor-support/spine/Slot.c \
    $$COCOS2DX_ROOT/cocos/editor-support/spine/SlotData.c \
    $$COCOS2DX_ROOT/cocos/editor-support/spine/TransformConstraint.c \
    $$COCOS2DX_ROOT/cocos/editor-support/spine/TransformConstraintData.c \
    $$COCOS2DX_ROOT/cocos/editor-support/spine/VertexAttachment.c

HEADERS += \
    $$COCOS2DX_ROOT/cocos/editor-support/spine/Animation.h \
    $$COCOS2DX_ROOT/cocos/editor-support/spine/AnimationState.h \
    $$COCOS2DX_ROOT/cocos/editor-support/spine/AnimationStateData.h \
    $$COCOS2DX_ROOT/cocos/editor-support/spine/Atlas.h \
    $$COCOS2DX_ROOT/cocos/editor-support/spine/AtlasAttachmentLoader.h \
    $$COCOS2DX_ROOT/cocos/editor-support/spine/Attachment.h \
    $$COCOS2DX_ROOT/cocos/editor-support/spine/AttachmentLoader.h \
    $$COCOS2DX_ROOT/cocos/editor-support/spine/AttachmentVertices.h \
    $$COCOS2DX_ROOT/cocos/editor-support/spine/Bone.h \
    $$COCOS2DX_ROOT/cocos/editor-support/spine/BoneData.h \
    $$COCOS2DX_ROOT/cocos/editor-support/spine/BoundingBoxAttachment.h \
    $$COCOS2DX_ROOT/cocos/editor-support/spine/Cocos2dAttachmentLoader.h \
    $$COCOS2DX_ROOT/cocos/editor-support/spine/Event.h \
    $$COCOS2DX_ROOT/cocos/editor-support/spine/EventData.h \
    $$COCOS2DX_ROOT/cocos/editor-support/spine/extension.h \
    $$COCOS2DX_ROOT/cocos/editor-support/spine/IkConstraint.h \
    $$COCOS2DX_ROOT/cocos/editor-support/spine/IkConstraintData.h \
    $$COCOS2DX_ROOT/cocos/editor-support/spine/Json.h \
    $$COCOS2DX_ROOT/cocos/editor-support/spine/kvec.h \
    $$COCOS2DX_ROOT/cocos/editor-support/spine/MeshAttachment.h \
    $$COCOS2DX_ROOT/cocos/editor-support/spine/PathAttachment.h \
    $$COCOS2DX_ROOT/cocos/editor-support/spine/PathConstraint.h \
    $$COCOS2DX_ROOT/cocos/editor-support/spine/PathConstraintData.h \
    $$COCOS2DX_ROOT/cocos/editor-support/spine/RegionAttachment.h \
    $$COCOS2DX_ROOT/cocos/editor-support/spine/Skeleton.h \
    $$COCOS2DX_ROOT/cocos/editor-support/spine/SkeletonAnimation.h \
    $$COCOS2DX_ROOT/cocos/editor-support/spine/SkeletonBatch.h \
    $$COCOS2DX_ROOT/cocos/editor-support/spine/SkeletonBinary.h \
    $$COCOS2DX_ROOT/cocos/editor-support/spine/SkeletonBounds.h \
    $$COCOS2DX_ROOT/cocos/editor-support/spine/SkeletonData.h \
    $$COCOS2DX_ROOT/cocos/editor-support/spine/SkeletonJson.h \
    $$COCOS2DX_ROOT/cocos/editor-support/spine/SkeletonRenderer.h \
    $$COCOS2DX_ROOT/cocos/editor-support/spine/Skin.h \
    $$COCOS2DX_ROOT/cocos/editor-support/spine/Slot.h \
    $$COCOS2DX_ROOT/cocos/editor-support/spine/SlotData.h \
    $$COCOS2DX_ROOT/cocos/editor-support/spine/spine-cocos2dx.h \
    $$COCOS2DX_ROOT/cocos/editor-support/spine/spine.h \
    $$COCOS2DX_ROOT/cocos/editor-support/spine/TransformConstraint.h \
    $$COCOS2DX_ROOT/cocos/editor-support/spine/TransformConstraintData.h \
    $$COCOS2DX_ROOT/cocos/editor-support/spine/VertexAttachment.h
