COCOS2DX_ROOT=$$PWD/../..

SOURCES += \
    $$COCOS2DX_ROOT/cocos/2d/CCAction.cpp \
    $$COCOS2DX_ROOT/cocos/2d/CCActionCamera.cpp \
    $$COCOS2DX_ROOT/cocos/2d/CCActionCatmullRom.cpp \
    $$COCOS2DX_ROOT/cocos/2d/CCActionEase.cpp \
    $$COCOS2DX_ROOT/cocos/2d/CCActionGrid.cpp \
    $$COCOS2DX_ROOT/cocos/2d/CCActionGrid3D.cpp \
    $$COCOS2DX_ROOT/cocos/2d/CCActionInstant.cpp \
    $$COCOS2DX_ROOT/cocos/2d/CCActionInterval.cpp \
    $$COCOS2DX_ROOT/cocos/2d/CCActionManager.cpp \
    $$COCOS2DX_ROOT/cocos/2d/CCActionPageTurn3D.cpp \
    $$COCOS2DX_ROOT/cocos/2d/CCActionProgressTimer.cpp \
    $$COCOS2DX_ROOT/cocos/2d/CCActionTiledGrid.cpp \
    $$COCOS2DX_ROOT/cocos/2d/CCActionTween.cpp \
    $$COCOS2DX_ROOT/cocos/2d/CCAnimation.cpp \
    $$COCOS2DX_ROOT/cocos/2d/CCAnimationCache.cpp \
    $$COCOS2DX_ROOT/cocos/2d/CCAtlasNode.cpp \
    $$COCOS2DX_ROOT/cocos/2d/CCAutoPolygon.cpp \
    $$COCOS2DX_ROOT/cocos/2d/CCCamera.cpp \
    $$COCOS2DX_ROOT/cocos/2d/CCCameraBackgroundBrush.cpp \
    $$COCOS2DX_ROOT/cocos/2d/CCClippingNode.cpp \
    $$COCOS2DX_ROOT/cocos/2d/CCClippingRectangleNode.cpp \
    $$COCOS2DX_ROOT/cocos/2d/CCComponent.cpp \
    $$COCOS2DX_ROOT/cocos/2d/CCComponentContainer.cpp \
    $$COCOS2DX_ROOT/cocos/2d/CCDrawingPrimitives.cpp \
    $$COCOS2DX_ROOT/cocos/2d/CCDrawNode.cpp \
    $$COCOS2DX_ROOT/cocos/2d/CCFastTMXLayer.cpp \
    $$COCOS2DX_ROOT/cocos/2d/CCFastTMXTiledMap.cpp \
    $$COCOS2DX_ROOT/cocos/2d/CCFont.cpp \
    $$COCOS2DX_ROOT/cocos/2d/CCFontAtlas.cpp \
    $$COCOS2DX_ROOT/cocos/2d/CCFontAtlasCache.cpp \
    $$COCOS2DX_ROOT/cocos/2d/CCFontCharMap.cpp \
    $$COCOS2DX_ROOT/cocos/2d/CCFontFNT.cpp \
    $$COCOS2DX_ROOT/cocos/2d/CCFontFreeType.cpp \
    $$COCOS2DX_ROOT/cocos/2d/CCGLBufferedNode.cpp \
    $$COCOS2DX_ROOT/cocos/2d/CCGrabber.cpp \
    $$COCOS2DX_ROOT/cocos/2d/CCGrid.cpp \
    $$COCOS2DX_ROOT/cocos/2d/CCLabel.cpp \
    $$COCOS2DX_ROOT/cocos/2d/CCLabelAtlas.cpp \
    $$COCOS2DX_ROOT/cocos/2d/CCLabelBMFont.cpp \
    $$COCOS2DX_ROOT/cocos/2d/CCLabelTextFormatter.cpp \
    $$COCOS2DX_ROOT/cocos/2d/CCLabelTTF.cpp \
    $$COCOS2DX_ROOT/cocos/2d/CCLayer.cpp \
    $$COCOS2DX_ROOT/cocos/2d/CCLight.cpp \
    $$COCOS2DX_ROOT/cocos/2d/CCMenu.cpp \
    $$COCOS2DX_ROOT/cocos/2d/CCMenuItem.cpp \
    $$COCOS2DX_ROOT/cocos/2d/CCMotionStreak.cpp \
    $$COCOS2DX_ROOT/cocos/2d/CCNode.cpp \
    $$COCOS2DX_ROOT/cocos/2d/CCNodeGrid.cpp \
    $$COCOS2DX_ROOT/cocos/2d/CCParallaxNode.cpp \
    $$COCOS2DX_ROOT/cocos/2d/CCParticleBatchNode.cpp \
    $$COCOS2DX_ROOT/cocos/2d/CCParticleExamples.cpp \
    $$COCOS2DX_ROOT/cocos/2d/CCParticleSystem.cpp \
    $$COCOS2DX_ROOT/cocos/2d/CCParticleSystemQuad.cpp \
    $$COCOS2DX_ROOT/cocos/2d/CCProgressTimer.cpp \
    $$COCOS2DX_ROOT/cocos/2d/CCProtectedNode.cpp \
    $$COCOS2DX_ROOT/cocos/2d/CCRenderTexture.cpp \
    $$COCOS2DX_ROOT/cocos/2d/CCScene.cpp \
    $$COCOS2DX_ROOT/cocos/2d/CCSprite.cpp \
    $$COCOS2DX_ROOT/cocos/2d/CCSpriteBatchNode.cpp \
    $$COCOS2DX_ROOT/cocos/2d/CCSpriteFrame.cpp \
    $$COCOS2DX_ROOT/cocos/2d/CCSpriteFrameCache.cpp \
    $$COCOS2DX_ROOT/cocos/2d/CCTextFieldTTF.cpp \
    $$COCOS2DX_ROOT/cocos/2d/CCTileMapAtlas.cpp \
    $$COCOS2DX_ROOT/cocos/2d/CCTMXLayer.cpp \
    $$COCOS2DX_ROOT/cocos/2d/CCTMXObjectGroup.cpp \
    $$COCOS2DX_ROOT/cocos/2d/CCTMXTiledMap.cpp \
    $$COCOS2DX_ROOT/cocos/2d/CCTMXXMLParser.cpp \
    $$COCOS2DX_ROOT/cocos/2d/CCTransition.cpp \
    $$COCOS2DX_ROOT/cocos/2d/CCTransitionPageTurn.cpp \
    $$COCOS2DX_ROOT/cocos/2d/CCTransitionProgress.cpp \
    $$COCOS2DX_ROOT/cocos/2d/CCTweenFunction.cpp

HEADERS += \
    $$COCOS2DX_ROOT/cocos/2d/CCAction.h \
    $$COCOS2DX_ROOT/cocos/2d/CCActionCamera.h \
    $$COCOS2DX_ROOT/cocos/2d/CCActionCatmullRom.h \
    $$COCOS2DX_ROOT/cocos/2d/CCActionEase.h \
    $$COCOS2DX_ROOT/cocos/2d/CCActionGrid.h \
    $$COCOS2DX_ROOT/cocos/2d/CCActionGrid3D.h \
    $$COCOS2DX_ROOT/cocos/2d/CCActionInstant.h \
    $$COCOS2DX_ROOT/cocos/2d/CCActionInterval.h \
    $$COCOS2DX_ROOT/cocos/2d/CCActionManager.h \
    $$COCOS2DX_ROOT/cocos/2d/CCActionPageTurn3D.h \
    $$COCOS2DX_ROOT/cocos/2d/CCActionProgressTimer.h \
    $$COCOS2DX_ROOT/cocos/2d/CCActionTiledGrid.h \
    $$COCOS2DX_ROOT/cocos/2d/CCActionTween.h \
    $$COCOS2DX_ROOT/cocos/2d/CCAnimation.h \
    $$COCOS2DX_ROOT/cocos/2d/CCAnimationCache.h \
    $$COCOS2DX_ROOT/cocos/2d/CCAtlasNode.h \
    $$COCOS2DX_ROOT/cocos/2d/CCAutoPolygon.h \
    $$COCOS2DX_ROOT/cocos/2d/CCCamera.h \
    $$COCOS2DX_ROOT/cocos/2d/CCCameraBackgroundBrush.h \
    $$COCOS2DX_ROOT/cocos/2d/CCClippingNode.h \
    $$COCOS2DX_ROOT/cocos/2d/CCClippingRectangleNode.h \
    $$COCOS2DX_ROOT/cocos/2d/CCComponent.h \
    $$COCOS2DX_ROOT/cocos/2d/CCComponentContainer.h \
    $$COCOS2DX_ROOT/cocos/2d/CCDrawingPrimitives.h \
    $$COCOS2DX_ROOT/cocos/2d/CCDrawNode.h \
    $$COCOS2DX_ROOT/cocos/2d/CCFastTMXLayer.h \
    $$COCOS2DX_ROOT/cocos/2d/CCFastTMXTiledMap.h \
    $$COCOS2DX_ROOT/cocos/2d/CCFont.h \
    $$COCOS2DX_ROOT/cocos/2d/CCFontAtlas.h \
    $$COCOS2DX_ROOT/cocos/2d/CCFontAtlasCache.h \
    $$COCOS2DX_ROOT/cocos/2d/CCFontCharMap.h \
    $$COCOS2DX_ROOT/cocos/2d/CCFontFNT.h \
    $$COCOS2DX_ROOT/cocos/2d/CCFontFreeType.h \
    $$COCOS2DX_ROOT/cocos/2d/CCGLBufferedNode.h \
    $$COCOS2DX_ROOT/cocos/2d/CCGrabber.h \
    $$COCOS2DX_ROOT/cocos/2d/CCGrid.h \
    $$COCOS2DX_ROOT/cocos/2d/CCLabel.h \
    $$COCOS2DX_ROOT/cocos/2d/CCLabelAtlas.h \
    $$COCOS2DX_ROOT/cocos/2d/CCLabelBMFont.h \
    $$COCOS2DX_ROOT/cocos/2d/CCLabelTextFormatter.h \
    $$COCOS2DX_ROOT/cocos/2d/CCLabelTTF.h \
    $$COCOS2DX_ROOT/cocos/2d/CCLayer.h \
    $$COCOS2DX_ROOT/cocos/2d/CCLight.h \
    $$COCOS2DX_ROOT/cocos/2d/CCMenu.h \
    $$COCOS2DX_ROOT/cocos/2d/CCMenuItem.h \
    $$COCOS2DX_ROOT/cocos/2d/CCMotionStreak.h \
    $$COCOS2DX_ROOT/cocos/2d/CCNode.h \
    $$COCOS2DX_ROOT/cocos/2d/CCNodeGrid.h \
    $$COCOS2DX_ROOT/cocos/2d/CCParallaxNode.h \
    $$COCOS2DX_ROOT/cocos/2d/CCParticleBatchNode.h \
    $$COCOS2DX_ROOT/cocos/2d/CCParticleExamples.h \
    $$COCOS2DX_ROOT/cocos/2d/CCParticleSystem.h \
    $$COCOS2DX_ROOT/cocos/2d/CCParticleSystemQuad.h \
    $$COCOS2DX_ROOT/cocos/2d/CCProgressTimer.h \
    $$COCOS2DX_ROOT/cocos/2d/CCProtectedNode.h \
    $$COCOS2DX_ROOT/cocos/2d/CCRenderTexture.h \
    $$COCOS2DX_ROOT/cocos/2d/CCScene.h \
    $$COCOS2DX_ROOT/cocos/2d/CCSprite.h \
    $$COCOS2DX_ROOT/cocos/2d/CCSpriteBatchNode.h \
    $$COCOS2DX_ROOT/cocos/2d/CCSpriteFrame.h \
    $$COCOS2DX_ROOT/cocos/2d/CCSpriteFrameCache.h \
    $$COCOS2DX_ROOT/cocos/2d/CCTextFieldTTF.h \
    $$COCOS2DX_ROOT/cocos/2d/CCTileMapAtlas.h \
    $$COCOS2DX_ROOT/cocos/2d/CCTMXLayer.h \
    $$COCOS2DX_ROOT/cocos/2d/CCTMXObjectGroup.h \
    $$COCOS2DX_ROOT/cocos/2d/CCTMXTiledMap.h \
    $$COCOS2DX_ROOT/cocos/2d/CCTMXXMLParser.h \
    $$COCOS2DX_ROOT/cocos/2d/CCTransition.h \
    $$COCOS2DX_ROOT/cocos/2d/CCTransitionPageTurn.h \
    $$COCOS2DX_ROOT/cocos/2d/CCTransitionProgress.h \
    $$COCOS2DX_ROOT/cocos/2d/CCTweenFunction.h
